name: Build & Deploy Web Flasher

on:
  push:
    paths:
      - 'src/**'
      - '*.ino'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Digispark Core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://digistump.com/package_digistump_index.json
          arduino-cli core update-index
          arduino-cli core install digistump:avr

      - name: Compile Firmware
        run: |
          mkdir -p build
          # Compile the root sketch which pulls in the src/ files
          arduino-cli compile --fqbn digistump:avr:digispark-tiny --output-dir ./build .
          mv ./build/*.hex ./build/roulette.hex

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./build/roulette.hex

  deploy-flasher:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Download Firmware
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: ./public/firmware

      - name: Generate Web Flasher
        run: |
          mkdir -p public
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Roulette Armory</title>
            <script src="https://cdn.jsdelivr.net/gh/skandhurkat/micronucleus-web@master/lib/micronucleus.js"></script>
            <style>
              body { background: #000; color: #0f0; font-family: 'Courier New', monospace; text-align: center; margin-top: 10%; }
              button { background: #000; color: #f00; border: 2px solid #f00; padding: 20px 40px; font-size: 24px; cursor: pointer; margin-top: 20px; }
              button:hover { background: #f00; color: #000; }
              #log { margin-top: 20px; color: #fff; }
            </style>
          </head>
          <body>
            <h1>/// ROULETTE BADUSB ///</h1>
            <p>1. Unplug Device.</p>
            <p>2. Click ARM.</p>
            <p>3. Plug in Device when prompted.</p>
            <button id="flashBtn">ARM DEVICE</button>
            <div id="log">Status: IDLE</div>
            
            <script>
              document.getElementById('flashBtn').addEventListener('click', async () => {
                const log = document.getElementById('log');
                try {
                  if (!navigator.usb) throw new Error("WebUSB not supported (Use Chrome/Edge)");
                  
                  log.innerText = "Status: DOWNLOADING FIRMWARE...";
                  const resp = await fetch('./firmware/roulette.hex');
                  if (!resp.ok) throw new Error("Firmware not found");
                  const firmware = await resp.arrayBuffer();

                  log.innerText = "Status: WAITING FOR DEVICE...";
                  const device = await navigator.usb.requestDevice({ filters: [{ vendorId: 0x16d0, productId: 0x0753 }] });
                  
                  log.innerText = "Status: FLASHING...";
                  const client = new Micronucleus(device);
                  await client.upload(new Uint8Array(firmware));
                  
                  log.innerText = "Status: COMPLETE. UNPLUG NOW.";
                  log.style.color = "#0f0";
                } catch (e) {
                  log.innerText = "ERROR: " + e.message;
                  log.style.color = "#f00";
                }
              });
            </script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
